config/routes.rb
Rails.application.routes.draw do
  resources :newsvilles
  root to: 'newsvilles#index'


end

app/models/newsville.rb
class Newsville < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  def google_news
    render text: 'This is the google news'
  end
end

app/controllers/newsvilles_controller.rb
class NewsvillesController < ApplicationController
  before_action :set_newsville, only: [:show, :edit, :update, :destroy]

  # GET /newsvilles
  # GET /newsvilles.json
  def index
    pages = Nokogiri::HTML(open('https://news.google.com/news'))
    @newsvilles = pages.css('.esc-body')
  end

  # GET /newsvilles/1
  # GET /newsvilles/1.json
  def show
  end

  # GET /newsvilles/new
  def new
    @newsville = Newsville.new
  end

  # GET /newsvilles/1/edit
  def edit
  end

  # POST /newsvilles
  # POST /newsvilles.json
  def create
    @newsville = Newsville.new(newsville_params)

    respond_to do |format|
      if @newsville.save
        format.html { redirect_to @newsville, notice: 'Newsville was successfully created.' }
        format.json { render :show, status: :created, location: @newsville }
      else
        format.html { render :new }
        format.json { render json: @newsville.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsvilles/1
  # PATCH/PUT /newsvilles/1.json
  def update
    respond_to do |format|
      if @newsville.update(newsville_params)
        format.html { redirect_to @newsville, notice: 'Newsville was successfully updated.' }
        format.json { render :show, status: :ok, location: @newsville }
      else
        format.html { render :edit }
        format.json { render json: @newsville.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsvilles/1
  # DELETE /newsvilles/1.json
  def destroy
    @newsville.destroy
    respond_to do |format|
      format.html { redirect_to newsvilles_url, notice: 'Newsville was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsville
      @newsville = Newsville.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsville_params
      params.require(:newsville).permit(:title, :body, :time, :image_url)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newsvilles_helper.rb
module NewsvillesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newsville</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    
    <%= yield %>
    
  </div>


</body>
</html>

app/views/newsvilles/_form.html.erb
<%= simple_form_for(@newsville) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :time %>
    <%= f.input :image_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/newsvilles/edit.html.erb
<h1>Editing Newsville</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsville %> |
<%= link_to 'Back', newsvilles_path %>

app/views/newsvilles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Latest On Newsvilles</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Time</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @newsvilles.each do |newsville| %>
      <tr>
        <td>
          <a target="_blank" href="<%= newsville.at_css('.esc-lead-article-title a')['href']%> ">
            <%= newsville.at_css('.titletext').text %>
          </a>
        </td>
        <td>
          <%= newsville.at_css('.esc-lead-snippet-wrapper').text %> <br><br>
          <a target="_blank" class="btn btn-default" href="<%= newsville.at_css('.esc-lead-article-title a')['href'] %>" role="button">Read More</a>
        </td>
        <td><%=  newsville.at_css('.al-attribution-timestamp').text %></td>
        <td><%= image_tag newsville.at_css('.esc-thumbnail-image')['src']  %></td>
        
        
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newsville', new_newsville_path %>

app/views/newsvilles/new.html.erb
<h1>New Newsville</h1>

<%= render 'form' %>

<%= link_to 'Back', newsvilles_path %>

app/views/newsvilles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @newsville.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @newsville.body %>
</p>

<p>
  <strong>Time:</strong>
  <%= @newsville.time %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @newsville.image_url %>
</p>

<%= link_to 'Edit', edit_newsville_path(@newsville) %> |
<%= link_to 'Back', newsvilles_path %>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>